Visibility of state variable section added
Developer-DAO/academy pull request #159
Opened 2022-09-30 08:09 UTC by shikhar360

## Changes

 #### Added one section in the "More on variables and types" content slide drawer , 
- The section defines the types of visibility of state variables 
- What should be the appropriate visibility that can be given to a variable

## API Updates

### New Features *(required)*

Fixes # 
Understanding about the visibility of variables.
Connects #
null

2022-09-30 13:07 UTC, 7i7o requested changes
Thanks a lot for your work @shikhar360 !!!

We are really happy that you managed to contribute and help us build this platform!

I'm adding some comments for you to change so we can merge your PR

Thanks a lot!!! 😊

2022-09-30 13:07 UTC, 7i7o commented on lessons/projects/1.mdx
> +powers**......and find the answers too!!!
For future reference, check if you modified lines by accident 😊 
In this case it's really not important, but in big PRs, it creates a little more unnecessary work for the reviewer.

2022-09-30 16:10 UTC, shikhar360 commented
I have made the requested changes @7i7o 😊 . Hope its good to go.

2022-10-06 12:24 UTC, PBillingsby commented
@7i7o is this good to go now?

2022-10-06 12:47 UTC, 7i7o requested changes
Hey @shikhar360 !
Thank you for your swift corrections, and sorry for being so busy to review this.

I added some **super minimal** language corrections, and it should be good to go

Ping me whenever you do this so we can merge ASAP 😊 

Also, thank you @PBillingsby for the ping 🙏

2022-10-06 12:47 UTC, 7i7o commented on lessons/projects/1.mdx
> +    - **Public**: If a state variable visibility is marked as `public` then those variables can be used within the smart contract and can be accessed by other contracts as well.Compilers automaticall
> ... as well.Compilers automatically generates functions ...

... as well. Compilers automatically generate functions ...

2022-10-06 15:22 UTC, shikhar360 commented
@7i7o Fixed the typos 😊 . You now can review this again

2022-10-06 15:43 UTC, 7i7o approved these changes
Everything is good to go!

2022-10-06 15:48 UTC, merged